# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(default='Clinic', max_length=50),
        ),
    ]
