# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_patient_dentist'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='announcement',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stat',
            name='coffee_intake',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='date_logged',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stat',
            name='has_flossed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stat',
            name='has_mouth_washed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stat',
            name='sugar_intake',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='times_brushed',
            field=models.IntegerField(default=0),
        ),
    ]
