# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20171017_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
